import sys

with open(r'c:\Users\GOODMAN\WHToolsBox\TVPackageMotionSim\run_drop_simulator\whts_radioss_builder.py', 'a', encoding='utf-8') as f:
    f.write('''
    def _write_lsdyna(self) -> "Path":
        """Export an LS-DYNA (.k) equivalent file for viewer compatibility."""
        import numpy as np
        path = self.out / f"{self.name}_LSDYNA.k"
        L = [
            "*KEYWORD",
            "*TITLE",
            "TVDrop LS-DYNA Model Generated by WHToolsBox",
            "*CONTROL_TERMINATION",
            " 0.05",
            "*CONTROL_TIMESTEP",
            " 0.0, 0.9",
        ]
        
        # Nodes and Elements
        for p in self._parts:
            L.append("*NODE")
            for nid, (x, y, z) in sorted(p.nodes.items()):
                L.append(f"{nid:>8d}{x:>16.5f}{y:>16.5f}{z:>16.5f}")
            
            if p.is_shell and p.quads:
                L.append("*ELEMENT_SHELL")
                for eid, ns in sorted(p.quads.items()):
                    L.append(f"{eid:>8d}{p.part_id:>8d}" + "".join([f"{n:>8d}" for n in ns]))
            elif (not p.is_shell) and p.hexas:
                L.append("*ELEMENT_SOLID")
                for eid, ns in sorted(p.hexas.items()):
                    L.append(f"{eid:>8d}{p.part_id:>8d}" + "".join([f"{n:>8d}" for n in ns]))

        # Parts
        for p in self._parts:
            L.append("*PART")
            L.append(f"{p.name}")
            L.append(f"{p.part_id:>10d}{p.part_id:>10d}{p.part_id:>10d}")

        # Materials & Sections
        rho = self._densities()
        def f10(val): return f"{val:>10.3e}"
        
        # 1 - Box (Shell)
        E_box = self.cfg.get('E_paper', 2000.0)
        L.append("*MAT_ELASTIC")
        L.append(f"{1:>10d}{f10(rho['box'])}{f10(E_box)}{f10(0.3)}")
        L.append("*SECTION_SHELL")
        L.append(f"{1:>10d}{10:>10d}{0:>10.3f}{0:>10d}{0:>10.3f}{0:>10.3f}{0:>10d}")
        L.append(f"{f10(self._geom.get('bt', 5.0))}")
        
        # 2, 3 - Cushion (Solid)
        for pid in [2, 3]:
            E_c = self.cfg.get('E_cushion', 10.0)
            L.append("*MAT_PIECEWISE_LINEAR_PLASTICITY")
            L.append(f"{pid:>10d}{f10(rho['cush'])}{f10(E_c)}{f10(0.3)}{f10(0.1)}{f10(100.0)}")
            L.append("*SECTION_SOLID")
            L.append(f"{pid:>10d}{1:>10d}")
            
        # 4 - OpenCell (Solid)
        E_oc = self.cfg.get('E_oc', 70000.0)
        L.append("*MAT_ELASTIC")
        L.append(f"{4:>10d}{f10(rho['oc'])}{f10(E_oc)}{f10(0.3)}")
        L.append("*SECTION_SOLID")
        L.append(f"{4:>10d}{1:>10d}")

        # 5 - Chassis (Shell)
        E_ch = self.cfg.get('E_chassis', 210000.0)
        L.append("*MAT_ELASTIC")
        L.append(f"{5:>10d}{f10(rho['ch'])}{f10(E_ch)}{f10(0.3)}")
        L.append("*SECTION_SHELL")
        L.append(f"{5:>10d}{2:>10d}")
        L.append(f"{f10(1.0)}")
        
        # 6 - Ground (Solid, MAT_RIGID)
        L.append("*MAT_RIGID")
        L.append(f"{6:>10d}{f10(rho['gnd'])}{f10(210000.0)}{f10(0.3)}")
        L.append(f"{1.0:>10.3f}{7:>10.3f}{7:>10.3f}")
        L.append("*SECTION_SOLID")
        L.append(f"{6:>10d}{1:>10d}")
        
        # Set Part for Package
        L.append("*SET_PART_LIST")
        L.append(f"{2:>10d}")
        L.append(f"{1:>10d}{2:>10d}{3:>10d}{4:>10d}{5:>10d}")
        
        # Initial Velocity
        omega_ms = np.linalg.norm(self.omega_vec) * 0.001
        v_mag = np.linalg.norm(self.v_vec)
        if omega_ms > 1e-6 or v_mag > 1e-6:
            axis = self.omega_vec / (np.linalg.norm(self.omega_vec) + 1e-12)
            L.append("*INITIAL_VELOCITY_GENERATION")
            L.append(f"{2:>10d}{2:>10d}{axis[0]:>10.3f}{axis[1]:>10.3f}{axis[2]:>10.3f}{self.v_vec[0]:>10.3f}{self.v_vec[1]:>10.3f}{self.v_vec[2]:>10.3f}")
            L.append(f"{0.0:>10.3f}{0.0:>10.3f}{0.0:>10.3f}{0.0:>10.3f}{0.0:>10.3f}{0.0:>10.3f}{0:>10d}")
            
        # Contact
        L.append("*CONTACT_AUTOMATIC_SINGLE_SURFACE")
        L.append(f"{0:>10d}{0:>10d}{3:>10d}")
        
        # Gravity
        L.append("*LOAD_BODY_Z")
        L.append(f"{1:>10d}")
        L.append("*DEFINE_CURVE")
        L.append(f"{1:>10d}{0:>10d}{1.0:>10.3f}{1.0:>10.3f}{0.0:>10.3f}{0.0:>10.3f}")
        G_MM_MS2 = 9.81e-3
        L.append(f"{0.0:>20.5f}{-G_MM_MS2:>20.5f}")
        L.append(f"{1.0:>20.5f}{-G_MM_MS2:>20.5f}")

        L.append("*END")
        
        path.write_text("\\n".join(L) + "\\n", encoding="utf-8")
        print(f"[LS-DYNA] K file -> {path.name}")
        return path
''')
