
import os

target_file = r'c:\Users\GOODMAN\WHToolsBox\TVPackageMotionSim\run_drop_simulator\plate_by_markers_v2.py'

with open(target_file, 'r', encoding='utf-8') as f:
    lines = f.readlines()

# ShellDeformationAnalyzer Restoration (Approx lines 404 to 615)
# We will identify the class start and the next class start to replace the interval.

start_idx = -1
end_idx = -1

for i, line in enumerate(lines):
    if line.startswith('class ShellDeformationAnalyzer:'):
        start_idx = i
    if line.startswith('class PlateAssemblyManager:'):
        end_idx = i
        break

if start_idx != -1 and end_idx != -1:
    new_class_content = [
        'class ShellDeformationAnalyzer:\n',
        '    """\n',
        '    [WHTOOLS] 통합 판 변형 분석기 (JAX 가속 버전)\n',
        '    개별 파트의 마커 데이터를 입력받아 자율적으로 좌표계를 설정하고, \n',
        '    강체 운동을 제거한 뒤 판 이론에 따른 구조 변형 해석을 수행합니다.\n',
        '    """\n',
        '    def __init__(self, W: float = 0, H: float = 0, \n',
        '                 thickness: float = 1.0, E: float = 70e9, \n',
        '                 nu: float = 0.3, name: str = "Part"):\n',
        '        self.name = name\n',
        '        self.W, self.H = W, H\n',
        '        self.thickness, self.E, self.nu = thickness, E, nu\n',
        '        \n',
        '        # 물리 해석 설정\n',
        '        self.cfg = PlateConfig(thickness=thickness, youngs_modulus=E, poisson_ratio=nu)\n',
        '        \n',
        '        # 데이터 관리\n',
        '        self.m_raw = None          # [Frames, Markers, 3] 원본 마커 히스토리\n',
        '        self.m_data_hist = None    # [Markers, Frames, 3] 분석용 (analyzer.m_data_hist 셰이프 호환용)\n',
        '        self.o_data = None         # [Markers, 2] 로컬 2D 좌표 (u, v)\n',
        '        self.o_data_hint = None    # 외부 좌표 힌트\n',
        '        \n',
        '        self.ref_markers = None    # [N, 3] 기준 마커\n',
        '        self.ref_basis = None      # [u, v, w] 로컬 기저\n',
        '        self.ref_center = None     # 초기 중심점\n',
        '        \n',
        '        self.sol = PlateMechanicsSolver(self.cfg)\n',
        '        self.results = {}\n',
        '\n',
        '    def run_analysis(self) -> bool:\n',
        '        """[WHTOOLS] 통합 해석 실행 및 예외 처리"""\n',
        '        try:\n',
        '            if self.m_raw is not None:\n',
        '                return self.analyze(self.m_raw, o_data_hint=self.o_data_hint)\n',
        '            elif self.m_data_hist is not None:\n',
        '                 return self.analyze(self.m_data_hist, o_data_hint=self.o_data_hint)\n',
        '        except Exception as e:\n',
        '            print(f"❌ Critical Error in {self.name}: {str(e)}")\n',
        '            import traceback\n',
        '            traceback.print_exc()\n',
        '        return False\n',
        '\n',
        '    def fit_reference_plane(self, m_data_init: np.ndarray) -> np.ndarray:\n',
        '        """[WHTOOLS] 초기 프레임 데이터를 이용한 로컬 평면 및 설계 좌표계 정의"""\n',
        '        self.ref_markers = np.array(m_data_init)\n',
        '        self.ref_center = np.mean(m_data_init, axis=0)\n',
        '        \n',
        '        # SVD를 이용한 주성분 분석 (PCA) -> 로컬 기저 벡터 산출\n',
        '        U, S, Vh = np.linalg.svd(self.ref_markers - self.ref_center)\n',
        '        self.ref_basis = Vh # [3, 3] matrix of row vectors (u, v, n)\n',
        '        \n',
        '        # 월드 좌표를 로컬 평면 (u, v)로 투영\n',
        '        self.o_data = (self.ref_markers - self.ref_center) @ self.ref_basis[:2].T\n',
        '        \n',
        '        if self.W == 0: self.W = float(np.max(self.o_data[:, 0]) - np.min(self.o_data[:, 0]))\n',
        '        if self.H == 0: self.H = float(np.max(self.o_data[:, 1]) - np.min(self.o_data[:, 1]))\n',
        '        \n',
        '        # 해석용 메쉬 그리드 설정 (Adaptive Margin)\n',
        '        r = self.cfg.margin_ratio\n',
        '        margin_x = np.clip(self.W * r, 3.0, 10.0)\n',
        '        margin_y = np.clip(self.H * r, 3.0, 10.0)\n',
        '        \n',
        '        min_x, max_x = np.min(self.o_data[:, 0]) - margin_x, np.max(self.o_data[:, 0]) + margin_x\n',
        '        min_y, max_y = np.min(self.o_data[:, 1]) - margin_y, np.max(self.o_data[:, 1]) + margin_y\n',
        '        self.sol.setup_mesh((min_x, max_x), (min_y, max_y))\n',
        '        return self.o_data\n',
        '\n',
        '    def remove_rigid_motion(self, m_data_frame: np.ndarray):\n',
        '        """\n',
        '        [WHTOOLS] Orthogonal Procrustes 기반 강체 운동 제거 (Forward Mapping 버전)\n',
        '        현재 프레임의 마커 셋을 기준 셋(Reference)과 최적으로 중첩시켜 순수 변형량을 추출합니다.\n',
        '        [Concept] Q_curr = (P_ref @ R + cq) 관계에서 R과 cq를 추출합니다.\n',
        '        """\n',
        '        if self.ref_markers is None:\n',
        '            return (None, None, None, None, None, None)\n',
        '            \n',
        '        curr_center = np.mean(m_data_frame, axis=0)\n',
        '        \n',
        '        # 1. P_c(Reference) -> Q_c(Current) 정방향 회전 산출\n',
        '        P_c = self.ref_markers - self.ref_center\n',
        '        Q_c = m_data_frame - curr_center\n',
        '        \n',
        '        # 2. 공분산 행렬 H = P^T @ Q (Forward: P -> Q)\n',
        '        H = P_c.T @ Q_c\n',
        '        U, S, Vt = np.linalg.svd(H)\n',
        '        \n',
        '        # 3. 회전 행렬 R = U @ Vt (P -> Q 매핑)\n',
        '        R = U @ Vt\n',
        '        if np.linalg.det(R) < 0:\n',
        '            R = U @ np.diag([1.0, 1.0, -1.0]) @ Vt\n',
        '            \n',
        '        # 4. 강체 운동 제거: 현재 마커 Q를 기준 좌표계 P로 정렬\n',
        '        # Q = P @ R 이 성립하므로 P = Q @ R.T 가 됨\n',
        '        m_rigid_aligned = Q_c @ R.T\n',
        '        \n',
        '        # 5. 성능 지표 산출 (Rigid Registration RMSE)\n',
        '        diff_vector = m_rigid_aligned - P_c\n',
        '        r_rmse = np.sqrt(np.mean(np.square(diff_vector[:, :2])))\n',
        '        \n',
        '        # 6. 로컬 면외 변위(Normal) 산출 (Reference Normal Basis 활용)\n',
        '        normal_displacement = diff_vector @ self.ref_basis[2]\n',
        '        \n',
        '        return (R, curr_center, self.ref_center, m_rigid_aligned, normal_displacement, r_rmse)\n',
        '\n',
        '    def analyze(self, m_data_hist: np.ndarray, o_data_hint: np.ndarray = None) -> bool:\n',
        '        """\n',
        '        [WHTOOLS] JAX 가속 엔진 배치 해석 (Full Cleanup & Stabilization)\n',
        '        """\n',
        '        m_data_hist = np.array(m_data_hist)\n',
        '        \n',
        '        # Shape 정규화\n',
        '        if o_data_hint is not None and m_data_hist.shape[1] != o_data_hint.shape[0]:\n',
        '            if m_data_hist.shape[0] == o_data_hint.shape[0]:\n',
        '                m_data_hist = np.swapaxes(m_data_hist, 0, 1)\n',
        '\n',
        '        n_frames, n_markers, _ = m_data_hist.shape\n',
        '        self.m_raw = m_data_hist \n',
        '        \n',
        '        if self.ref_markers is None:\n',
        '            self.fit_reference_plane(m_data_hist[0])\n',
        '            \n',
        '        if o_data_hint is not None:\n',
        '            self.o_data = o_data_hint\n',
        '            self.W = float(np.max(self.o_data[:, 0]) - np.min(self.o_data[:, 0]))\n',
        '            self.H = float(np.max(self.o_data[:, 1]) - np.min(self.o_data[:, 1]))\n',
        '            r = self.cfg.margin_ratio\n',
        '            margin_x, margin_y = np.clip(self.W*r, 3, 10), np.clip(self.H*r, 3, 10)\n',
        '            self.sol.setup_mesh((np.min(self.o_data[:, 0])-margin_x, np.max(self.o_data[:, 0])+margin_x),\n',
        '                                (np.min(self.o_data[:, 1])-margin_y, np.max(self.o_data[:, 1])+margin_y))\n',
        '            \n',
        '        # 강체 운동 제거 및 로컬 변위 추출\n',
        '        all_w, all_R, all_cq, all_rmses = [], [], [], []\n',
        '        for i in range(n_frames):\n',
        '            R, cq, cp, m_aligned, w_disp, r_rmse = self.remove_rigid_motion(m_data_hist[i])\n',
        '            all_w.append(w_disp)\n',
        '            all_R.append(R)\n',
        '            all_cq.append(cq)\n',
        '            all_rmses.append(r_rmse)\n',
        '            \n',
        '        all_displacement_w = np.stack(all_w) \n',
        '        \n',
        '        # 차수 적응 장치 (Markers-Density Aware)\n',
        '        def count_unique(coords, tol=1e-3):\n',
        '            sorted_coords = np.sort(coords)\n',
        '            diffs = np.diff(sorted_coords)\n',
        '            return np.sum(diffs > tol) + 1\n',
        '\n',
        '        n_unique_x = count_unique(self.o_data[:, 0])\n',
        '        n_unique_y = count_unique(self.o_data[:, 1])\n',
        '        \n',
        '        deg_x = min(self.cfg.poly_degree, n_unique_x - 1)\n',
        '        deg_y = min(self.cfg.poly_degree, n_unique_y - 1)\n',
        '        \n',
        '        aspect_ratio = max(self.W, self.H) / (min(self.W, self.H) + 1e-9)\n',
        '        if aspect_ratio > 8.0:\n',
        '            if self.W < self.H: deg_x = min(deg_x, 2)\n',
        '            else:               deg_y = min(deg_y, 2)\n',
        '\n',
        '        self.sol.optimizer = AdvancedPlateOptimizer(degree_x=deg_x, degree_y=deg_y)\n',
        '        \n',
        '        # JAX 솔버 구동\n',
        '        all_displacement_w_rel = all_displacement_w - all_displacement_w[0]\n',
        '        q_loc_jax = jnp.zeros((n_frames, n_markers, 3))\n',
        '        q_loc_jax = q_loc_jax.at[:, :, 0].set(self.o_data[:, 0])\n',
        '        q_loc_jax = q_loc_jax.at[:, :, 1].set(self.o_data[:, 1])\n',
        '        q_loc_jax = q_loc_jax.at[:, :, 2].set(jnp.array(all_displacement_w_rel))\n',
        '\n',
        '        p_ref_jax = jnp.column_stack([self.o_data, jnp.zeros(n_markers)])\n',
        '        params, rmses, norm_stats = self.sol.optimizer.solve_analytical(q_loc_jax, p_ref_jax, self.cfg.reg_lambda)\n',
        '        batch_results = self.sol.evaluate_batch(params, norm_stats)\n',
        '\n',
        '        # 결과 패키징\n',
        '        self.results = {k: np.array(v) for k, v in batch_results.items()}\n',
        '        self.results.update({\n',
        '            \'R\': np.stack(all_R),\n',
        '            \'c_Q\': np.stack(all_cq),\n',
        '            \'c_P\': np.repeat(self.ref_center[None, :], n_frames, axis=0),\n',
        '            \'Q_local\': np.array(q_loc_jax),\n',
        '            \'rmse\': np.array(rmses),\n',
        '            \'r_rmse\': np.array(all_rmses),\n',
        '            \'Marker Local Disp. [mm]\': all_displacement_w\n',
        '        })\n',
        '        \n',
        '        max_marker_disp = np.max(np.abs(all_displacement_w_rel))\n',
        '        max_fit_disp = np.max(np.abs(self.results[\'Displacement [mm]\']))\n',
        '        \n',
        '        warn_str = ""\n',
        '        if max_fit_disp > max_marker_disp * 1.5 and max_marker_disp > 0.1:\n',
        '            warn_str = f" ⚠️ [WARN] Fit displacement ({max_fit_disp:.2f}mm) exceeds markers ({max_marker_disp:.2f}mm)!"\n',
        '            \n',
        '        print(f"  > [PART-OK] {self.name:<24} analyzed. (Avg F-RMSE: {np.mean(rmses):.2e} mm, Avg R-RMSE: {np.mean(all_rmses):.2e} mm) [{deg_x}x{deg_y}]{warn_str}")\n',
        '        return True\n',
        '\n'
    ]
    lines[start_idx:end_idx] = new_class_content

# update_frame cleaning (Approx lines 1334 to 1345)
# Fixing spacing and potential fragments

for i, line in enumerate(lines):
    if 'if view_mode == "Global":' in line:
        lines[i+1] = '                # [WHTOOLS] P_local -> Q_world 변환 (Forward Mapping)\n'
        lines[i+2] = '                p_world_oriented = p_deformed @ basis\n'
        lines[i+3] = '                info[\'poly\'].points = p_world_oriented @ R + cq\n'
        lines[i+4] = '                info[\'m_poly\'].points = np.array(analyzer.m_raw[frame_idx])\n'
        # Remove extra blank lines if any
        if 'info[\'poly\'].points = p_deformed' in lines[i+6]:
             # It means there are intermediate lines to remove
             pass

with open(target_file, 'w', encoding='utf-8') as f:
    f.writelines(lines)

print("Restoration finished.")
