[Executables]
# ---------------------------------------------------------
# 외부 프로그램 실행 파일 경로 설정
# ---------------------------------------------------------

# ParaView: VTKHDF 포맷 등 시각화를 위한 경로
# 환경변수 PATH에 등록되어 있다면 그냥 'paraview' 라고 적어도 무방합니다.
paraview_path = C:\Program Files\ParaView 6.0.1\bin\paraview.exe

# LS-PrePost: Radioss (.k) 및 LS-DYNA (d3plot) 결과 시각화용 경로
# 환경변수 PATH에 등록되어 있다면 그냥 'lspp48' 등으로 적어도 무방합니다.
ls_prepost_path = C:\Program Files\LSTC\LS-PrePost 2024R2(4.11)\lsprepost4.11.exe

# OpenRadioss 엔진 실행 파일(exec 폴더 안의 starter/engine)이 위치한 최상위 경로
openradioss_dir = D:\OpenRadioss_win64\OpenRadioss
