# -*- coding: utf-8 -*-
"""
autocalculix_api.py
===================
CalculiX 분석을 위한 공용 외부 API 인터페이스 모듈.
외부 프로젝트(WHT_LightChassisModel)에서 메쉬 노드, 요소, 재료 성분 및 
경계/하중 조건을 받아 동적으로 INP 파일을 생성하고 CalculiX를 구동하여 
후처리된 가시화 데이터(.vtu) 및 수치 결과(주파수 등)를 반환합니다.
"""

from pathlib import Path
import sys

BASE_DIR = Path(__file__).resolve().parent.parent
if str(BASE_DIR) not in sys.path:
    sys.path.append(str(BASE_DIR))

from src.core.config import CALCULIX_EXE
from src.core.solver import CalculixSolver
from src.core.dat_parser import CalculixDatParser
from src.core.frd_converter import FrdToVtuConverter


def run_calculix_analysis(
    nodes: dict,
    elements: list,
    properties: dict,
    analysis_type: str,
    analysis_config: dict,
    bcs: list = None,
    forces: list = None,
    workspace_dir: str = None
) -> dict:
    """
    외부에서 넘겨받은 메쉬 및 해석 설정을 바탕으로 CalculiX FEM 해석을 실행하고 결과를 반환합니다.

    Parameters
    ----------
    nodes : dict
        노드 좌표 딕셔너리. 형식: {nid: (x, y, z)} (mm 단위)
    elements : list
        요소 토폴로지 리스트. 형식: [(eid, element_type, [node_ids], pid)]
        (예: `[(1, "QUAD4", [101, 102, 103, 104], 1)]`)
    properties : dict
        섹션 및 재료 속성 딕셔너리. 형식: {pid: (thickness, E, nu, rho)}
        (E: MPa, nu: 포아송비, rho: ton/mm³ 단위)
    analysis_type : str
        해석 유형. "modal" (고유진동수 해석) 또는 "static" (선형 정적 해석)
    analysis_config : dict
        해석용 상세 설정값.
        - "job_name" (str): 해석 잡 이름 (기본값: "ccx_job")
        - "num_modes" (int): 모달 해석 시 추출할 모드 개수 (기본값: 10)
    bcs : list, optional
        정적 해석용 SPC 경계 구속조건 리스트. 형식: [(node_id, [dofs], value)]
        (dofs는 0-based 정수형 리스트, 예: [0, 1, 2] -> X, Y, Z 구속, 기본값: None)
    forces : list, optional
        정적 해석용 집중 외력 및 모멘트 리스트. 형식: [(node_id, [fx, fy, fz, mx, my, mz])]
        (기본값: None)
    workspace_dir : str, optional
        해석 파일(INP, DAT, FRD 등)을 생성하고 실행할 임시 작업 디렉토리 경로.
        지정하지 않을 경우 AutoCalculix 내부 workspace 폴더를 사용합니다.

    Returns
    -------
    dict
        해석 결과 정보를 담은 딕셔너리.
        - "type" (str): "modal" 또는 "static"
        - "job_name" (str): 실행된 잡 이름
        - "workspace" (str): 실행 작업 디렉토리 경로
        - "frequencies" (list): 모달 해석의 경우 파싱된 고유진동수 리스트 [{"mode": int, "hz": float}, ...]
        - "vtu_base" (str): 변환된 VTU 가시화 파일의 베이스 파일 경로 (확장자 제외)
    """
    # 1. 작업 디렉토리 설정
    work_path = Path(workspace_dir) if workspace_dir else BASE_DIR / "workspace"
    work_path.mkdir(parents=True, exist_ok=True)
    
    job_name = analysis_config.get("job_name", "ccx_analysis")
    print(f"[AutoCalculix API] Preparing job '{job_name}' in workspace: {work_path}")
    
    # 2. 메쉬 INP 파일 동적 작성
    mesh_filename = f"{job_name}_mesh.inp"
    mesh_inp_path = work_path / mesh_filename
    
    with open(mesh_inp_path, 'w', encoding='utf-8') as f:
        f.write("** Generated by AutoCalculix API for WHT Topography Monitor\n")
        
        # Nodes 기록
        f.write("*NODE\n")
        for nid, (x, y, z) in sorted(nodes.items()):
            f.write(f"{nid}, {x:.10g}, {y:.10g}, {z:.10g}\n")
            
        # Elements 분할 수집 (속성 PID 별로 ELSET을 분류하여 적층)
        elset_elems = {}
        for eid, etype, conn, pid in elements:
            elset_name = f"ELSET_PROP_{pid}"
            elset_elems.setdefault((etype, elset_name), []).append((eid, conn))
            
        for (etype, elset_name), elem_list in elset_elems.items():
            # meshio type 또는 WHT type을 CalculiX 셸 코드로 매핑
            ccx_type = "S4" if "QUAD" in etype.upper() else "S3"
            f.write(f"\n*ELEMENT, TYPE={ccx_type}, ELSET={elset_name}\n")
            for eid, conn in elem_list:
                conn_str = ", ".join(str(n) for n in conn)
                f.write(f"{eid}, {conn_str}\n")
                
    print(f"[AutoCalculix API] Created mesh file: {mesh_filename} ({len(nodes)} nodes, {len(elements)} elements)")

    # 3. Master .inp 빌드 및 스텝(STEP) 시나리오 구성
    master_inp_path = work_path / f"{job_name}.inp"
    with open(master_inp_path, 'w', encoding='utf-8') as f:
        f.write(f"*HEADING\nCalculiX Dynamic Job: {job_name}\n")
        f.write(f"*INCLUDE, INPUT={mesh_filename}\n\n")
        
        # 재료(MAT) 및 셸 단면 두께(SHELL SECTION) 기록
        for pid, (t, E, nu, rho) in properties.items():
            mat_name = f"MAT_PROP_{pid}"
            f.write(f"*MATERIAL, NAME={mat_name}\n")
            f.write(f"*ELASTIC\n{E}, {nu}\n")
            f.write(f"*DENSITY\n{rho}\n\n")
            
            f.write(f"*SHELL SECTION, ELSET=ELSET_PROP_{pid}, MATERIAL={mat_name}\n")
            f.write(f"{t}\n\n")
            
        # Boundary Conditions (SPC) 매핑 (STEP 시작 전에 전역으로 적용하거나 STEP 내 공통 적용)
        if bcs:
            f.write("*BOUNDARY\n")
            for nid, dofs, val in bcs:
                # dofs는 0-based 리스트이므로 CalculiX용 1-based 자유도로 변환
                for d in dofs:
                    f.write(f"{nid}, {d+1}, {d+1}, {val:.8f}\n")

        # STEP 구문 시작
        f.write("*STEP\n")
        
        # 3-1) 모달 해석 분기
        if analysis_type.lower() == "modal":
            num_modes = analysis_config.get("num_modes", 10)
            f.write("*FREQUENCY\n")
            f.write(f"{num_modes}\n")
            f.write("*NODE FILE\nU\n") # 변위 모드 형상 출력
            
        # 3-2) 정적 해석 분기
        else:
            f.write("*STATIC\n")
            
            # Concentrated Loads (FORCE) 매핑
            if forces:
                f.write("*CLOAD\n")
                for nid, f_vec in forces:
                    # f_vec = [fx, fy, fz, mx, my, mz]
                    for idx, val in enumerate(f_vec):
                        if abs(val) > 1e-12:
                            f.write(f"{nid}, {idx+1}, {val:.8f}\n")
                            
            f.write("*NODE FILE\nU\n") # 변위 출력
            f.write("*EL FILE\nS\n")  # 엘리먼트 셸 응력(Stress) 출력
            
        f.write("*END STEP\n")
        
    print(f"[AutoCalculix API] Created master analysis file: {master_inp_path.name}")
    
    # 4. CalculiX 솔버 실행
    solver = CalculixSolver(CALCULIX_EXE)
    solver.run(job_name, work_path)
    
    # 5. 결과 취합 및 후처리 변환
    result_data = {
        "type": analysis_type.lower(),
        "job_name": job_name,
        "workspace": str(work_path),
        "frequencies": [],
        "vtu_base": ""
    }
    
    # 5-1) 모달 해석 고유진동수 데이터 파싱 (.dat)
    if analysis_type.lower() == "modal":
        dat_file = work_path / f"{job_name}.dat"
        if dat_file.exists():
            parser = CalculixDatParser()
            result_data["frequencies"] = parser.extract_frequencies(dat_file)
            print(f"[AutoCalculix API] Parsed {len(result_data['frequencies'])} modes successfully.")
            
    # 5-2) FRD -> VTU 변환 실행
    frd_file = work_path / f"{job_name}.frd"
    if frd_file.exists():
        print(f"[AutoCalculix API] Converting FRD to VTU formats...")
        converter = FrdToVtuConverter()
        vtu_base = converter.convert(frd_file)
        if vtu_base:
            result_data["vtu_base"] = str(vtu_base)
            print(f"[AutoCalculix API] Post-processing completed. VTU base path: {vtu_base}")
    else:
        print("[AutoCalculix API] [Warning] Result .frd file not found. Analysis may have failed.")
        
    return result_data
